spring.application.name=user-management-api

spring.datasource.url=jdbc:postgresql://localhost:5432/user_management
spring.datasource.username=abdrakhmanzhasulan
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true